// <auto-generated />
namespace myPassionProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EventLocationFK2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EventLocationFK2));
        
        string IMigrationMetadata.Id
        {
            get { return "202402241734395_EventLocationFK2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
